### Registrar
POST http://localhost:3000/v1/signUp
Content-Type: application/json

{
  "name":"omars",
  "lastname":"jiji",
  "username":"sirSosa",
  "password": "micontraseña",
  "email": "omar@gmail.com"
}

### LogIn
POST http://localhost:3000/v1/login
Content-Type: application/json

{
  "password": "micontraseña",
  "email": "juanito@gmail.com"
}

### get profile
GET http://localhost:3000/v1/profile/fa32ca8b-f47a-11ef-9610-d8bbc1ab39d3

### post post
POST http://localhost:3000/v1/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzEzMyw4Niw4LDIyOCwyNDQsMTM2LDE3LDIzOSwxNTAsMTYsMjE2LDE4NywxOTMsMTcxLDU3LDIxMV19LCJlbWFpbCI6Im9tYXJAZ21haWwuY29tIiwiaWF0IjoxNzQwNjA1MjY4LCJleHAiOjE3NDA2NDg0Njh9.eteITPlRPln1gc0Zp2K6gGPMkNSVR6AlSnmEsqaBRUQ
Content-Type: application/json

{
  "content": "omar post 11",
  "media_url": "http://example.com/image.jpg"
}

### delete post
DELETE http://localhost:3000/v1/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzI1MCw1MCwyMDIsMTM5LDI0NCwxMjIsMTcsMjM5LDE1MCwxNiwyMTYsMTg3LDE5MywxNzEsNTcsMjExXX0sImVtYWlsIjoianVhbml0b0BnbWFpbC5jb20iLCJpYXQiOjE3NDA1OTk0NTMsImV4cCI6MTc0MDYwMzA1M30.6egrUSJUacVSbGcHAYsKI0fcYpjTfeIUma70fJVi_nA
Content-Type: application/json

{
  "post_id": "2ed13c1d-f47b-11ef-9610-d8bbc1ab39d3"
}

### get posts
GET  http://localhost:3000/v1/posts
Content-Type: application/json

{
  "page": 2
}

### get followee posts
GET  http://localhost:3000/v1/followeePosts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzI1MCw1MCwyMDIsMTM5LDI0NCwxMjIsMTcsMjM5LDE1MCwxNiwyMTYsMTg3LDE5MywxNzEsNTcsMjExXX0sImVtYWlsIjoianVhbml0b0BnbWFpbC5jb20iLCJpYXQiOjE3NDA2MDU0NDIsImV4cCI6MTc0MDY0ODY0Mn0.nCBEb2ranE9pJnPYOBqOk6Pp8FTCwdidVbMo4pFAwps
Content-Type: application/json

{
  "page": 1
}

### post like
POST http://localhost:3000/v1/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzEzMiwxMzEsMjQ5LDEzNiwyNDMsMjQ2LDE3LDIzOSwxODAsNzQsMjE2LDE4NywxOTMsMTcxLDU3LDIxMV19LCJlbWFpbCI6Imp1YW5pdG9AZ21haWwuY29tIiwiaWF0IjoxNzQwNTkzMDg4LCJleHAiOjE3NDA1OTY2ODh9.yQnusd4mmwO1SphXdDYdL-gLsCM3WMu9J7bR1RxcQjY
Content-Type: application/json

{
  "post_id": "b7c8b880-f46d-11ef-9610-d8bbc1ab39d3"
}

### remove like
DELETE  http://localhost:3000/v1/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzEzMiwxMzEsMjQ5LDEzNiwyNDMsMjQ2LDE3LDIzOSwxODAsNzQsMjE2LDE4NywxOTMsMTcxLDU3LDIxMV19LCJlbWFpbCI6Imp1YW5pdG9AZ21haWwuY29tIiwiaWF0IjoxNzQwNTkzMDg4LCJleHAiOjE3NDA1OTY2ODh9.yQnusd4mmwO1SphXdDYdL-gLsCM3WMu9J7bR1RxcQjY
Content-Type: application/json

{
  "post_id": "b7c8b880-f46d-11ef-9610-d8bbc1ab39d3"
}
### post comment
POST http://localhost:3000/v1/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzI1MCw1MCwyMDIsMTM5LDI0NCwxMjIsMTcsMjM5LDE1MCwxNiwyMTYsMTg3LDE5MywxNzEsNTcsMjExXX0sImVtYWlsIjoianVhbml0b0BnbWFpbC5jb20iLCJpYXQiOjE3NDA2MDE4MjgsImV4cCI6MTc0MDY0NTAyOH0.c59EhwK3uxlmY_aoqNk5wpYlcKItl0k7_VEZxM0gpAI
Content-Type: application/json

{
  "content": "comment 12",
  "post_id": "1398e270-f480-11ef-9610-d8bbc1ab39d3"
}

###get comment
GET http://localhost:3000/v1/comment
Content-Type: application/json

{
  "page": 1,
  "post_id": "1398e270-f480-11ef-9610-d8bbc1ab39d3"
}

###delete comment
DELETE  http://localhost:3000/v1/comment
Content-Type: application/json

{
  "post_id": "1398e270-f480-11ef-9610-d8bbc1ab39d3"
}

### follow user
POST http://localhost:3000/v1/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzI1MCw1MCwyMDIsMTM5LDI0NCwxMjIsMTcsMjM5LDE1MCwxNiwyMTYsMTg3LDE5MywxNzEsNTcsMjExXX0sImVtYWlsIjoianVhbml0b0BnbWFpbC5jb20iLCJpYXQiOjE3NDA2MDU0NDIsImV4cCI6MTc0MDY0ODY0Mn0.nCBEb2ranE9pJnPYOBqOk6Pp8FTCwdidVbMo4pFAwps
Content-Type: application/json

{
  "followee_id": "855608e4-f488-11ef-9610-d8bbc1ab39d3"
}

### unfollow user
DELETE  http://localhost:3000/v1/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzI1MCw1MCwyMDIsMTM5LDI0NCwxMjIsMTcsMjM5LDE1MCwxNiwyMTYsMTg3LDE5MywxNzEsNTcsMjExXX0sImVtYWlsIjoianVhbml0b0BnbWFpbC5jb20iLCJpYXQiOjE3NDA2MDU0NDIsImV4cCI6MTc0MDY0ODY0Mn0.nCBEb2ranE9pJnPYOBqOk6Pp8FTCwdidVbMo4pFAwps
Content-Type: application/json

{
  "followee_id": "855608e4-f488-11ef-9610-d8bbc1ab39d3"
}

