### Registrar
POST http://localhost:3000/v1/signUp
Content-Type: application/json

{
  "name":"juan",
  "lastname":"jijojijo",
  "username":"xXjuanitoXx",
  "password": "micontraseña",
  "email": "juanito@gmail.com"
}

### LogIn
POST http://localhost:3000/v1/login
Content-Type: application/json

{
  "password": "micontraseña",
  "email": "juanito@gmail.com"
}

### get profile
GET http://localhost:3000/v1/profile/fa32ca8b-f47a-11ef-9610-d8bbc1ab39d3

### post post
POST http://localhost:3000/v1/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzcsOTYsMTM3LDI1MCwyNDQsMTY4LDE3LDIzOSwxNTAsMTYsMjE2LDE4NywxOTMsMTcxLDU3LDIxMV19LCJlbWFpbCI6Im9tYXJAZ21haWwuY29tIiwiaWF0IjoxNzQwNjE4ODE1LCJleHAiOjE3NDA2NjIwMTV9.CDtLFhVzSD1EzEBsG1pfA-64NWh7Lf9pIbP4s4-QQdY
Content-Type: application/json

{
  "content": "omar post 10",
  "media_url": "http://example.com/image.jpg"
}

### delete post
DELETE http://localhost:3000/v1/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzcsOTYsMTM3LDI1MCwyNDQsMTY4LDE3LDIzOSwxNTAsMTYsMjE2LDE4NywxOTMsMTcxLDU3LDIxMV19LCJlbWFpbCI6Im9tYXJAZ21haWwuY29tIiwiaWF0IjoxNzQwNjE4ODE1LCJleHAiOjE3NDA2NjIwMTV9.CDtLFhVzSD1EzEBsG1pfA-64NWh7Lf9pIbP4s4-QQdY
Content-Type: application/json

{
  "post_id": "3cc8c4eb-f4a8-11ef-9610-d8bbc1ab39d3"
}

### get posts
GET  http://localhost:3000/v1/posts
Content-Type: application/json

{
  "page": 1
}

### get followee posts
GET  http://localhost:3000/v1/followeePosts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzI1MCw1MCwyMDIsMTM5LDI0NCwxMjIsMTcsMjM5LDE1MCwxNiwyMTYsMTg3LDE5MywxNzEsNTcsMjExXX0sImVtYWlsIjoianVhbml0b0BnbWFpbC5jb20iLCJpYXQiOjE3NDA2MDU0NDIsImV4cCI6MTc0MDY0ODY0Mn0.nCBEb2ranE9pJnPYOBqOk6Pp8FTCwdidVbMo4pFAwps
Content-Type: application/json

{
  "page": 1
}

### post like
POST http://localhost:3000/v1/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzcsOTYsMTM3LDI1MCwyNDQsMTY4LDE3LDIzOSwxNTAsMTYsMjE2LDE4NywxOTMsMTcxLDU3LDIxMV19LCJlbWFpbCI6Im9tYXJAZ21haWwuY29tIiwiaWF0IjoxNzQwNjE4ODE1LCJleHAiOjE3NDA2NjIwMTV9.CDtLFhVzSD1EzEBsG1pfA-64NWh7Lf9pIbP4s4-QQdY
Content-Type: application/json

{
  "post_id": "35ed3515-f4a8-11ef-9610-d8bbc1ab39d3"
}

### remove like
DELETE  http://localhost:3000/v1/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzcsOTYsMTM3LDI1MCwyNDQsMTY4LDE3LDIzOSwxNTAsMTYsMjE2LDE4NywxOTMsMTcxLDU3LDIxMV19LCJlbWFpbCI6Im9tYXJAZ21haWwuY29tIiwiaWF0IjoxNzQwNjE4ODE1LCJleHAiOjE3NDA2NjIwMTV9.CDtLFhVzSD1EzEBsG1pfA-64NWh7Lf9pIbP4s4-QQdY
Content-Type: application/json

{
  "post_id": "35ed3515-f4a8-11ef-9610-d8bbc1ab39d3"
}
### post comment
POST http://localhost:3000/v1/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzcsOTYsMTM3LDI1MCwyNDQsMTY4LDE3LDIzOSwxNTAsMTYsMjE2LDE4NywxOTMsMTcxLDU3LDIxMV19LCJlbWFpbCI6Im9tYXJAZ21haWwuY29tIiwiaWF0IjoxNzQwNjE4ODE1LCJleHAiOjE3NDA2NjIwMTV9.CDtLFhVzSD1EzEBsG1pfA-64NWh7Lf9pIbP4s4-QQdY
Content-Type: application/json

{
  "content": "comment 7",
  "post_id": "35ed3515-f4a8-11ef-9610-d8bbc1ab39d3"
}

###get comment
GET http://localhost:3000/v1/comment
Content-Type: application/json

{
  "page": 1,
  "post_id": "35ed3515-f4a8-11ef-9610-d8bbc1ab39d3"
}

###delete comment
DELETE  http://localhost:3000/v1/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzcsOTYsMTM3LDI1MCwyNDQsMTY4LDE3LDIzOSwxNTAsMTYsMjE2LDE4NywxOTMsMTcxLDU3LDIxMV19LCJlbWFpbCI6Im9tYXJAZ21haWwuY29tIiwiaWF0IjoxNzQwNjE4ODE1LCJleHAiOjE3NDA2NjIwMTV9.CDtLFhVzSD1EzEBsG1pfA-64NWh7Lf9pIbP4s4-QQdY
Content-Type: application/json

{
  "comment_id": "c4512b54-f4b2-11ef-9610-d8bbc1ab39d3"
}

### follow user
POST http://localhost:3000/v1/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzIyNCwyNTUsMjUsMSwyNDQsMTg5LDE3LDIzOSwxNTAsMTYsMjE2LDE4NywxOTMsMTcxLDU3LDIxMV19LCJlbWFpbCI6Imp1YW5pdG9AZ21haWwuY29tIiwiaWF0IjoxNzQwNjczMzY5LCJleHAiOjE3NDA3MTY1Njl9.MVjCwQS5mkcgc905ZQ_GIAiu-6QyVEEtXuvEz4ajArY
Content-Type: application/json

{
  "followee_id": "076089fa-f4a8-11ef-9610-d8bbc1ab39d3"
}

### unfollow user
DELETE  http://localhost:3000/v1/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzIyNCwyNTUsMjUsMSwyNDQsMTg5LDE3LDIzOSwxNTAsMTYsMjE2LDE4NywxOTMsMTcxLDU3LDIxMV19LCJlbWFpbCI6Imp1YW5pdG9AZ21haWwuY29tIiwiaWF0IjoxNzQwNjczMzY5LCJleHAiOjE3NDA3MTY1Njl9.MVjCwQS5mkcgc905ZQ_GIAiu-6QyVEEtXuvEz4ajArY
Content-Type: application/json

{
  "followee_id": "076089fa-f4a8-11ef-9610-d8bbc1ab39d3"
}

### save post
POST http://localhost:3000/v1/savepost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzcsOTYsMTM3LDI1MCwyNDQsMTY4LDE3LDIzOSwxNTAsMTYsMjE2LDE4NywxOTMsMTcxLDU3LDIxMV19LCJlbWFpbCI6Im9tYXJAZ21haWwuY29tIiwiaWF0IjoxNzQwNjE4ODE1LCJleHAiOjE3NDA2NjIwMTV9.CDtLFhVzSD1EzEBsG1pfA-64NWh7Lf9pIbP4s4-QQdY
Content-Type: application/json

{
  "post_id": "3a1c373a-f4a8-11ef-9610-d8bbc1ab39d3"
}

### unsave post
DELETE  http://localhost:3000/v1/savepost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzcsOTYsMTM3LDI1MCwyNDQsMTY4LDE3LDIzOSwxNTAsMTYsMjE2LDE4NywxOTMsMTcxLDU3LDIxMV19LCJlbWFpbCI6Im9tYXJAZ21haWwuY29tIiwiaWF0IjoxNzQwNjE4ODE1LCJleHAiOjE3NDA2NjIwMTV9.CDtLFhVzSD1EzEBsG1pfA-64NWh7Lf9pIbP4s4-QQdY
Content-Type: application/json

{
  "post_id": "3a1c373a-f4a8-11ef-9610-d8bbc1ab39d3"
}

### get saved posts
GET http://localhost:3000/v1/savepost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzcsOTYsMTM3LDI1MCwyNDQsMTY4LDE3LDIzOSwxNTAsMTYsMjE2LDE4NywxOTMsMTcxLDU3LDIxMV19LCJlbWFpbCI6Im9tYXJAZ21haWwuY29tIiwiaWF0IjoxNzQwNjE4ODE1LCJleHAiOjE3NDA2NjIwMTV9.CDtLFhVzSD1EzEBsG1pfA-64NWh7Lf9pIbP4s4-QQdY
Content-Type: application/json

{
  "page": 1
}

### get followers
GET http://localhost:3000/v1/followers/076089fa-f4a8-11ef-9610-d8bbc1ab39d3

### get followees
GET http://localhost:3000/v1/following/076089fa-f4a8-11ef-9610-d8bbc1ab39d3
