### Registrar
POST http://localhost:3000/v1/signUp
Content-Type: application/json

{
  "name":"juanito",
  "lastname":"perez",
  "username":"xXjuanitoXx",
  "password": "micontraseña",
  "email": "juanito@gmail.com"
}

### LogIn
POST http://localhost:3000/v1/login
Content-Type: application/json

{
  "password": "micontraseña",
  "email": "juanito@gmail.com"
}

### get profile
GET http://localhost:3000/v1/profile/8483f988-f3f6-11ef-b44a-d8bbc1ab39d3

### post post
POST http://localhost:3000/v1/uploadpost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzEzMiwxMzEsMjQ5LDEzNiwyNDMsMjQ2LDE3LDIzOSwxODAsNzQsMjE2LDE4NywxOTMsMTcxLDU3LDIxMV19LCJlbWFpbCI6Imp1YW5pdG9AZ21haWwuY29tIiwiaWF0IjoxNzQwNTkzMDg4LCJleHAiOjE3NDA1OTY2ODh9.yQnusd4mmwO1SphXdDYdL-gLsCM3WMu9J7bR1RxcQjY
Content-Type: application/json

{
  "content": "hola mundo",
  "media_url": "http://example.com/image.jpg"
}


### MAKE AN ORDER

POST http://localhost:3000/v1/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNDgxMWY2Ni0wMTg1LTExZWYtYWM4Mi1kOGJiYzFhYjM5ZDMiLCJ1c2VyRW1haWwiOiJqdWFuaXRvQGdtYWlsLmNvbSIsImlhdCI6MTcxMzg4NTkwMiwiZXhwIjoxNzEzOTI5MTAyfQ.4NS6yPO0hzzc0tCsjFwU9WAiJZIrTJtPXp2g7JVVZQQ

Content-Type: application/json
{
  "orderId":"9iwefju9f8jifou89u",
  "productId":"54wgwfewrrgfwwe",
  "name":"la cosa",
  "color":"black",
  "size":"large",
  "price":50.99,
  "quantity":3, 
  "subtotal":152.97, 
  "img":"ifjwiejwoejfwio.jpg"
}

### get cart
GET http://localhost:3000/v1/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1NTVlMGNmZS0wMTg4LTExZWYtYWM4Mi1kOGJiYzFhYjM5ZDMiLCJ1c2VyRW1haWwiOiJvbWFyLnNvc2EucXVpbWljYUBnbWFpbC5jb20iLCJpYXQiOjE3MTM4ODcwNTcsImV4cCI6MTcxMzkzMDI1N30.mlb2i0ZiUYLFZH_vg8Rkn6wobebCy70nqlkK8Sc1c00

### delete from cart
DELETE http://localhost:3000/v1/cart/9e8827ad-01a2-11ef-ac82-d8bbc1ab39d3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1NTVlMGNmZS0wMTg4LTExZWYtYWM4Mi1kOGJiYzFhYjM5ZDMiLCJ1c2VyRW1haWwiOiJvbWFyLnNvc2EucXVpbWljYUBnbWFpbC5jb20iLCJpYXQiOjE3MTM4ODcwNTcsImV4cCI6MTcxMzkzMDI1N30.mlb2i0ZiUYLFZH_vg8Rkn6wobebCy70nqlkK8Sc1c00